### ISSUE TITLE
Fails on go mod download

### ISSUE THREAD

**Issue by RohitRox** [gbrlsnchs/jwt#14]
Adding `gbrlsnchs/jwt` to a `go.mod` file
and running `go mod download`
is giving this error
```
go: github.com/gbrlsnchs/jwt@v0.0.0-20180914181710-808efa0714ba: go.mod has post-v0 module path "github.com/gbrlsnchs/jwt/v2" at revision 808efa0714ba
go: error loading module requirements
```

Go Version: `go1.11.4 darwin/amd64`

**Comment by gbrlsnchs** [comment]
I think you should add `github.com/gbrlsnchs/jwt/v2` (with the suffix) to your `go.mod` file, since it's in `v2` already. If you don't, I think you have to specify a `v1` version (`github.com/gbrlsnchs/jwt@v1.1.0`), otherwise `go mod` tries to fetch the most recent commit, which has a `/v2` suffix in its `go.mod`, thus breaking.

**Comment by RohitRox** [comment]
I see what you mean.
Thank you for explaining.
