### ISSUE TITLE
Get Logged User Information

### ISSUE THREAD

**Issue by jassonha21** [gbrlsnchs/jwt#15]
Hi, 
I'm still new with authentication thing
How can i get the user information through the token?
is it okay if i input user detail such as name, email, etc in the `Token` struct?
then is it okay if i unmarshal the token and return the information inside the Token?

**Comment by gbrlsnchs** [comment]
Hello there.

> How can i get the user information through the token?

To retrieve information from a JWT, you have to:
1. Have a struct representing the token (be it `jwt.JWT` or any struct that has it embedded)
2. Parse the JWT token string
3. Unmarshal the payload content returned from the parsing function into your struct

> is it okay if i input user detail such as name, email, etc in the Token struct?

This depends entirely on your application. I would advise against it since it makes the JWT bigger. Also, any sensitive information would be available client-side. I, **personally**, prefer to only make the user's unique ID available. This way I can retrieve their information server side, from whatever source I desire.

> then is it okay if i unmarshal the token and return the information inside the Token?

I think if you rely on the JWT as a cache for user information, you might run into some annoying issues, as the JWT can be manipulated client-side and you'll end up having to validate the token every time it hits your servers.

I hope I could guide you. I'll leave this open for a while or until you find my answer is satisfactory.

**Comment by jassonha21** [comment]
> This depends entirely on your application. I would advise against it since it makes the JWT bigger. Also, any sensitive information would be available client-side. I, personally, prefer to only make the user's unique ID available. This way I can retrieve their information server side, from whatever source I desire.

if i do it this way, then every time i need the user data i will retrieve the data from database?  From the uniqueID. is the unique ID = user ID here? 


thanks for the response 😬

**Comment by gbrlsnchs** [comment]
> if i do it this way, then every time i need the user data i will retrieve the data from database?

It can be from wherever you want, i.e. from an in-memory cache, a not-as-fast database, a file (don't do this :laughing:), etc.. it's up to you to decide. Again, storing sensitive data in the JWT not only makes it grow in size, but also makes it confidential and thus vulnerable, since it is accessible client-side. You wouldn't want your JWT, with sensitive user information, posted on pastebin sites, would you?

> From the uniqueID. is the unique ID = user ID here?

Yes, the user's unique ID. Put it in the subject claim and validate it server-side. With it, you can search for user information server side wherever you want, as pointed previously.

**Comment by jassonha21** [comment]
> > if i do it this way, then every time i need the user data i will retrieve the data from database?
> 
> It can be from wherever you want, i.e. from an in-memory cache, a not-as-fast database, a file (don't do this 😆), etc.. it's up to you to decide. Again, storing sensitive data in the JWT not only makes it grow in size, but also makes it confidential and thus vulnerable, since it is accessible client-side. You wouldn't want your JWT, with sensitive user information, posted on pastebin sites, would you?
> 
> > From the uniqueID. is the unique ID = user ID here?
> 
> Yes, the user's unique ID. Put it in the subject claim and validate it server-side. With it, you can search for user information server side wherever you want, as pointed previously.

i see 😲 i understand it now
thanks for pointing it out 😆 

thanks @gbrlsnchs for explaining so clearly 😭 

i will close this question 👍
