### ISSUE TITLE
why all the pointers?

### ISSUE THREAD

**Issue by henderjon** [gbrlsnchs/jwt#16]
Maybe I'm missing something, but why do you recommend embedding a pointer in your claims and why embed a pointer to [header](https://github.com/gbrlsnchs/jwt/blob/master/jwt.go#L14)?

I have nothing against pointers in general, but I don't think they're necessary [here](https://github.com/gbrlsnchs/jwt#first-create-a-custom-type-and-embed-a-jwt-pointer-in-it) or [here](https://github.com/gbrlsnchs/jwt#now-initialize-marshal-and-sign-it) (please correct me) and if they're not necessary, I tend to avoid using them...

I'm mostly just curious.

**Comment by gbrlsnchs** [comment]
Good question. I think they don't need to be there too, and perhaps their inclusion was purely arbitrary by the time I wrote `v2`. I apologize for that.

I want it to change for `v3`, which I want to release when generics are implemented in Go. I don't think releasing `v3` before a big change like generics is a good idea since it'll make `v3` obsolete too soon and it is too hard and painful for developers (mainly the ones from companies of whichever size) to upgrade major versions.

I'll leave this open until this is fixed somehow, enabling someone that thinks those pointers are the right fit can speak out until then.

**Comment by gbrlsnchs** [comment]
@henderjon, while I was working on `v3`, I realized that the JWT claims should indeed be a pointer in order to avoid allocation when not used (i.e. a token with empty claims section). Allocating a pointer to a claims struct would be better than allocating a full claims struct despite not needing it. Not the case for the header, as it will always be present and have at least one field set.
