### ISSUE TITLE
RawToken doesn't verify if the Algorithm is supported by the verifier 

### ISSUE THREAD

**Issue by metala** [gbrlsnchs/jwt#27]
I am looking at the `master` branch.

The Verify() func doesn't check the header `alg` against the verifier it was provided. While I don't see vulnerability here, like the one that verifies ES256 with HS256 verifier[1], as far as I can tell, it doesn't comply with the specification[2]. In the general case, RawToken.Verify() should check if the Verifier is suitable for the specific token `alg` and otherwise return an error.   

Refs:
[1] https://auth0.com/blog/critical-vulnerabilities-in-json-web-token-libraries/
[2] https://tools.ietf.org/html/rfc7519 Section 7.2 Article 5

**Comment by gbrlsnchs** [comment]
Regarding [1], yes, it's not a concern here because the choice of which verifier to use is, by default*, not chosen by the library itself, but by the server. The server having to build signing method (signer and verifier) structs with contained keys itself guarantees that no arbitrary verifiers are used.

About [2], you have a valid point there. If it's up to the server choosing which signing method to use, why not verify on-the-fly what's being received? I'll have to rework `RawToken` internally so it can store a `Header` when `jwt.Parse` is called in order to check it when `RawToken.Verify` is called. Changing that is theoretically trivial and won't break the current API, since `RawToken.Decode` will still return the header that's stored in it.

\* As long as the server doesn't choose a verifier based on the `alg` field. Even so, the server would still need to build signing methods to be picked, so the asymmetric key vulnerability wouldn't happen, but the `none` vulnerability would still be possible if the server had a `None` verifier available and programmed to be chosen accordingly.

**Comment by gbrlsnchs** [comment]
@metala once I rewrite tests, this will be released in the next `beta` pre-release. Meanwhile, I would love to hear your feedback about the new kid on the block, [`Decoder`](https://godoc.org/github.com/gbrlsnchs/jwt#Decoder). It does exactly what you requested here when decoding the token but also facilitates the steps. You can also verify `alg` separately by running [`Header.Validate`](https://godoc.org/github.com/gbrlsnchs/jwt#Header.Validate).

**Comment by metala** [comment]
I will take a look after the weekend.

**Comment by metala** [comment]
I have tested it locally on a project of mine. I like the `NewDecoder().Decode()` thing, It's pretty straightforward. Thanks.
