### ISSUE TITLE
ID validator does not verify uniqueness

### ISSUE THREAD

**Issue by sworisbreathing** [gbrlsnchs/jwt#3]
Per [RFC 7519](https://tools.ietf.org/html/rfc7519#section-4.1.7):

> The "jti" (JWT ID) claim provides a unique identifier for the JWT... The "jti" claim can be used
   to prevent the JWT from being replayed.

The [current implementation](https://github.com/gbrlsnchs/jwt/blob/6912d8fd72d62417b5bbb5af1d9bce1b0e834765/validators.go#L70) of jti validation simply looks for an exact match against a specified value. So it's not so much looking for uniqueness across different JWTs, but rather that the JWT has a pre-defined ID.

**Comment by gbrlsnchs** [comment]
Thanks for the feedback. I think you've got a point there, mate. I don't think that validator is of any help as it currently is. But I think we should discuss and decide (and maybe have a third opinion?) about the issue. Also, we should consider the new situations it'll create:
- First, changing that validator's signature might imply that a new major version should be released, as it would break the public API. This is not a big issue since it's just a matter of bumping the version using `go mod`, easy as pie, but going from `v2` to `v3` just because of that seems like a huge step to take. We should be sure that it doesn't affect others too much. I think it doesn't, but who knows?
- Also, what should be the proper logic for that function? Should we do a linear search in an array of strings?

I'm open to talk about these as I think it is an important improvement and it should be definitely made.

**Comment by sworisbreathing** [comment]
- If you're following semver, then you could keep the same major version by adding a new `ValidatorFunc`, possibly deprecating the older one.
- I'd keep it simple - check for an existing token with the same ID and compare signatures. Reject it if the signatures don't match.

Since JWTs are typically passed by external clients, and it's a pretty common pattern to handle requests in a goroutine, the logic needs to be thread-safe. Also you need to think about how long you want tokens to hang around for the `jti` check. I'd also put a recommendation in the docs that users add it after other validators. That way you're only checking/storing valid tokens.

If you're storing them in memory, then you'll need cache semantics so the tokens don't end up hogging all your memory. Something like zpatrick/go-cache might work - you could set the entry's time-to-live based on `exp` if it's provided, and a sane/configurable fallback ttl (say, 24 hours?) if it isn't.

If you're persisting them, then it depends on your persistent store as to how you go about it, and you might also have to implement your own eviction algorithm, depending on what features you get from the persistence layer.
