### ISSUE TITLE
What's the difference between verifying and validating?

### ISSUE THREAD

**Issue by taadis** [gbrlsnchs/jwt#34]
RT...

**Comment by gbrlsnchs** [comment]
`jwt.Verify` verifies the JWT signature.

Validation is about validating the JWT claims (check whether "exp" is expired, "aud" is included in desired audiences, etc).

The reason `jwt.Verify` doesn't validate claims by default is because it is optional and application-specific. However, verifying the signature is mandatory.

Is it clear now? Let me know!

**Comment by taadis** [comment]
em...got
