### ISSUE TITLE
golang.org/x/xerrors removal

### ISSUE THREAD

**Issue by gertcuykens** [gbrlsnchs/jwt#39]
Consider removing golang.org/x/xerrors dependency. I know it doesn't matter using type aliases but still I prefer deprecating it sooner than later :) Thanks. JWT is the only dependency in my mod list that relies on xerrors.

**Comment by gbrlsnchs** [comment]
I can't remove `golang.org/x/xerrors` dependency since that is used to keep compatibility with Go versions 1.11 and 1.12.

If you're using Go 1.13 or newer, this lib will use the built-in `errors` API. It will list/download `golang.org/x/xerrors` as a dependency though, but it won't show in your final binary.
