### ISSUE TITLE
Extract claims without jwt verification

### ISSUE THREAD

**Issue by kotyara85** [gbrlsnchs/jwt#47]
Hi,
Is there a way to decode claims without passing a secret?
It's required something before the actual token verification
Right now it's mandatory to pass hs
Thanks

**Comment by metala** [comment]
```
import "encoding/base64"

parts := strings.Split(token, ".")
part := parts[1]
payload, err := base64.RawURLEncoding.DecodeString(part)
```

You need to add error checks

**Comment by gbrlsnchs** [comment]
My intention when designing the API was indeed to avoid parsing the token without verifying it. I don't plan to change that, since I value a safer usage.

Unfortunately the token is just a Base64-encoded JSON, so it's easily parsable. Obfuscating with encryption would add one more layer in order for the user to parse, but still doesn't solve the problem, which is ingrained in JWT: the ability to store data in a security token.
