### ISSUE TITLE
Will `sub` support other types? For example, int/map...

### ISSUE THREAD

**Issue by noecs** [gbrlsnchs/jwt#51]
Will the `sub` type of the payload support other data types?

I noticed that in some other projects, `sub` may be a map or an int type. Does `sub` have plans to support other types in the future?

**Comment by gbrlsnchs** [comment]
The reason it is string only is because I'm following [the RFC for the JWT spec](https://datatracker.ietf.org/doc/html/rfc7519#section-4.1.2), and for this case, more specifically where it says:
> The "sub" value is a case-sensitive string containing a StringOrURI value.

I suggest converting values to their respective string formats beforehand. Applications should be responsible for this kind of conversion, and we don't want to try to be too smart here, it would only add complexity, complexity this which would never satisfy everybody's use case.

I'll close this but if you feel I'm missing something, please let me know! :smiley:
